### ISSUE TITLE
RoR group project: set up your Kanban board Review

### ISSUE THREAD

**Issue by Felipeg005** [Felipeg005/Recipe-App-Rails#8]
## Next actions were taken to set up the project's kanban board:

- [x] Create an empty repository for your group project.
- [x] Open the GitHub project (Kanban board)
- [x] Create tasks on Kanban board based on the project requirements.
- [x] Each task it's on a separate card that:
- [x] Has a descriptive title.
- [x] Has the number of points in the [Xpt] prefix. 
- [x] Has a description of the task.

### This project it's developed for just 1 person that is me 😄 

Thanks for your review

**Comment by dasileker** [comment]
## **Hi @Felipeg005 ,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
